# Generated by Django 5.2.1 on 2025-06-01 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='group_composition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.IntegerField(verbose_name='Группа')),
                ('student', models.IntegerField(verbose_name='Обучающийся')),
            ],
        ),
        migrations.CreateModel(
            name='groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsible_person', models.IntegerField(verbose_name='Ответственное лицо')),
                ('status', models.CharField(max_length=200, verbose_name='Статус')),
                ('direction', models.CharField(max_length=200, verbose_name='Напрвление')),
            ],
        ),
        migrations.CreateModel(
            name='logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table', models.CharField(max_length=200, verbose_name='Таблица')),
                ('operation', models.CharField(max_length=200, verbose_name='Вид операции')),
                ('number', models.IntegerField(verbose_name='id Записи')),
                ('date', models.DateField(verbose_name='Дата')),
                ('user', models.IntegerField(verbose_name='Совершено')),
            ],
        ),
        migrations.CreateModel(
            name='organizations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование')),
                ('ogrn', models.CharField(max_length=200, verbose_name='ОГРН')),
                ('inn', models.CharField(max_length=200, verbose_name='ИНН')),
                ('kpp', models.CharField(max_length=200, verbose_name='КПП')),
            ],
        ),
        migrations.CreateModel(
            name='students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=200, verbose_name='Фамилия')),
                ('surname', models.CharField(max_length=200, verbose_name='Отчество')),
                ('passport_number', models.CharField(max_length=200, verbose_name='Номер паспорта')),
                ('date_of_birth', models.DateField(verbose_name='Дата рождения')),
                ('address_birth', models.CharField(max_length=200, verbose_name='Место рождения')),
                ('address', models.CharField(max_length=200, verbose_name='Адрес')),
                ('snils', models.CharField(max_length=200, verbose_name='СНИЛС')),
                ('education', models.CharField(max_length=200, verbose_name='Документ об образовании')),
                ('passport_issued', models.CharField(max_length=200, verbose_name='Паспорт выдан')),
                ('group', models.IntegerField(verbose_name='Группа')),
                ('organization', models.IntegerField(verbose_name='Организация')),
                ('medical_certificate', models.CharField(max_length=200, verbose_name='Медицинская справка')),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=200, verbose_name='Фамилия')),
                ('surname', models.CharField(max_length=200, verbose_name='Отчество')),
                ('title', models.CharField(max_length=200, verbose_name='Должность')),
                ('login', models.CharField(max_length=200, verbose_name='Логин')),
                ('password', models.CharField(max_length=200, verbose_name='Пароль')),
            ],
        ),
    ]
