# Generated by Django 5.2.1 on 2025-06-02 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='group',
        ),
    ]
